apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: ctse-assignment-3
name: ctse-assignment-3
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: ctse-assignment-3
status:
  loadBalancer: {}